### ISSUE TITLE
Add configurable keyspace for metric publishing

### ISSUE THREAD

**Issue by skonefal** [intelsdi-x/snap-plugin-publisher-cassandra#30]
Similar to https://github.com/intelsdi-x/snap-plugin-publisher-rabbitmq/issues/4, not every Cassandra user has rights to create keyspaces, and plugin should not try to do it by default.

This improvement proposes:
1) User should be able to choose desired keyspace in plugin configuration
2) Plugin should not try to create keyspace (except when explicitly ordered via configuration maybe?)

**Comment by squall0gd** [comment]
Done!
